/**
 * LOCAL DEVELOPMENT ONLY — SPEC §10: replays the anonymized worklog through the real production
 * workflow engine (task creation, status moves, scoring hooks) with the historical times, then prints a
 * reconciliation of WORKER credits per person against the CSV (PD-010: QC credit is per task, so the
 * Checking rows become qc assignments, not tasks).
 *
 *   npx tsx scripts/seed-from-worklog.ts \
 *     --rules ../docs/retouch/seed/seed_credit_rules_T5_2026.csv \
 *     --log ../docs/retouch/seed/seed_worklog_T5_2026.csv [--inflight 0.1] [--seed 42]
 *
 * Idempotent: previous seed jobs (tag "seed") and their tasks, logs and score entries are removed first.
 * Seed account passwords are written to BE/.env.seed-worklog (git-ignored) and never printed.
 */
import { randomBytes } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

import "dotenv/config";

import { closeDatabase, getSql } from "../src/db/client.js";
import type { QuerySql } from "../src/lib/db-types.js";
import { closeRedis } from "../src/lib/redis.js";
import { resolveAccessContext } from "../src/modules/access/access-context.js";
import { importCreditRules } from "../src/modules/production/credit-rules.js";
import { parseCsv } from "../src/modules/production/csv.js";
import { loadTask, loadWorkflowModel, type TaskRow } from "../src/modules/production/jobs.repo.js";
import { insertTasks, moveTask, settleJob } from "../src/modules/production/tasks.service.js";
import { addDays } from "../src/modules/production/time.js";
import { statusByCode, type Workflow } from "../src/modules/production/workflow.js";

// Arguments & safety -------------------------------------------------------------------------------------

const args = new Map<string, string>();
for (let index = 2; index < process.argv.length; index += 1) {
  const key = process.argv[index]!;
  if (key.startsWith("--")) {
    args.set(key.slice(2), process.argv[index + 1] && !process.argv[index + 1]!.startsWith("--") ? process.argv[++index]! : "true");
  }
}
const rulesPath = resolve(args.get("rules") ?? "../docs/retouch/seed/seed_credit_rules_T5_2026.csv");
const logPath = resolve(args.get("log") ?? "../docs/retouch/seed/seed_worklog_T5_2026.csv");
const inflight = Number(args.get("inflight") ?? "0");
let randomState = Number(args.get("seed") ?? "42") >>> 0 || 42;
const random = () => {
  // Deterministic xorshift so a given --seed reproduces the same in-flight sample.
  randomState ^= randomState << 13;
  randomState ^= randomState >>> 17;
  randomState ^= randomState << 5;
  return (randomState >>> 0) / 4_294_967_296;
};

const isLoopback = (value: string) => {
  try {
    const host = new URL(value).hostname;
    return host === "127.0.0.1" || host === "localhost" || host === "[::1]";
  } catch {
    return false;
  }
};
const supabaseUrl = process.env.SUPABASE_URL ?? "";
const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY ?? "";
if (!isLoopback(supabaseUrl) || !isLoopback(process.env.DATABASE_URL ?? "") || !serviceKey) {
  console.error("Refusing to seed: SUPABASE_URL and DATABASE_URL must point at the local stack.");
  process.exit(1);
}
if (!(inflight >= 0 && inflight <= 1)) {
  console.error("--inflight must be between 0 and 1.");
  process.exit(1);
}

// Accounts ---------------------------------------------------------------------------------------------------

type SeedAccount = { key: string; email: string; name: string; roles: string[] };
const staffKeys = Array.from({ length: 15 }, (_, index) => `NV${String(index + 1).padStart(2, "0")}`);
const accounts: SeedAccount[] = [
  ...staffKeys.map((key) => ({ key, email: `${key.toLowerCase()}@test.local`, name: key, roles: ["STAFF"] })),
  { key: "LEAD01", email: "lead01@test.local", name: "LEAD01", roles: ["LEADER", "QC"] },
  { key: "ACC01", email: "acc01@test.local", name: "ACC01", roles: ["ACCOUNT"] },
  { key: "ADMIN01", email: "admin01@test.local", name: "ADMIN01", roles: ["ADMIN"] }
];
const passwordFile = new URL("../.env.seed-worklog", import.meta.url);

const loadPasswords = () => {
  const values = new Map<string, string>();
  if (existsSync(passwordFile)) {
    for (const line of readFileSync(passwordFile, "utf8").split(/\r?\n/)) {
      const match = /^SEED_([A-Z0-9]+)_PASSWORD=(.+)$/.exec(line.trim());
      if (match?.[1] && match[2]) {
        values.set(match[1], match[2]);
      }
    }
  }
  for (const account of accounts) {
    if (!values.has(account.key)) {
      values.set(account.key, `Seed-${randomBytes(9).toString("base64url")}`);
    }
  }
  writeFileSync(
    passwordFile,
    `# Worklog seed accounts (git-ignored). Generated by scripts/seed-from-worklog.ts\n${accounts
      .map((account) => `SEED_${account.key}_EMAIL=${account.email}\nSEED_${account.key}_PASSWORD=${values.get(account.key)}`)
      .join("\n")}\n`
  );
  return values;
};

const ensureAccounts = async (sql: QuerySql, organizationId: string) => {
  const passwords = loadPasswords();
  const memberRole = (await sql<{ id: string }[]>`SELECT id FROM public.roles WHERE organization_id = ${organizationId} AND key = 'member' AND deleted_at IS NULL`)[0];
  if (!memberRole) {
    throw new Error('Role "member" not found — run scripts/seed-dev-users.ts first.');
  }
  const ids = new Map<string, string>();
  for (const account of accounts) {
    let id = (await sql<{ id: string }[]>`SELECT id FROM auth.users WHERE lower(email) = ${account.email}`)[0]?.id;
    if (!id) {
      const response = await fetch(new URL("/auth/v1/admin/users", supabaseUrl), {
        method: "POST",
        headers: { apikey: serviceKey, authorization: `Bearer ${serviceKey}`, "content-type": "application/json" },
        body: JSON.stringify({ email: account.email, password: passwords.get(account.key), email_confirm: true, user_metadata: { display_name: account.name } })
      });
      if (response.status >= 300) {
        throw new Error(`Creating ${account.email} failed with ${response.status}`);
      }
      id = (await sql<{ id: string }[]>`SELECT id FROM auth.users WHERE lower(email) = ${account.email}`)[0]?.id;
    }
    if (!id) {
      throw new Error(`Account ${account.email} missing`);
    }
    await sql`
      INSERT INTO public.app_users (id, email, display_name) VALUES (${id}, ${account.email}, ${account.name})
      ON CONFLICT (id) DO UPDATE SET display_name = EXCLUDED.display_name, deleted_at = NULL
    `;
    await sql`
      INSERT INTO public.organization_memberships (organization_id, user_id, role_id, status, joined_at)
      VALUES (${organizationId}, ${id}, ${memberRole.id}, 'active', now())
      ON CONFLICT (organization_id, user_id) WHERE deleted_at IS NULL DO UPDATE SET status = 'active'
    `;
    await sql`
      INSERT INTO production.user_roles (organization_id, user_id, role_code)
      SELECT ${organizationId}, ${id}, unnest(${account.roles}::text[]) ON CONFLICT DO NOTHING
    `;
    ids.set(account.key, id);
  }
  // Two report teams, staff split evenly.
  const teams: string[] = [];
  for (const name of ["Seed Team A", "Seed Team B"]) {
    teams.push(
      (
        await sql<{ id: string }[]>`
          INSERT INTO production.teams (organization_id, name) VALUES (${organizationId}, ${name})
          ON CONFLICT (organization_id, lower(name)) DO UPDATE SET active = true RETURNING id
        `
      )[0]!.id
    );
  }
  for (const [index, key] of staffKeys.entries()) {
    await sql`
      INSERT INTO production.member_profiles (organization_id, user_id, team_id) VALUES (${organizationId}, ${ids.get(key)!}, ${teams[index % 2]!})
      ON CONFLICT (organization_id, user_id) DO UPDATE SET team_id = EXCLUDED.team_id
    `;
  }
  // KPI target per SPEC §10.2 (company file, Q2): 2400 points for May 2026.
  for (const key of staffKeys) {
    await sql`
      INSERT INTO production.kpi_targets (organization_id, user_id, period_type, target_points, effective_from, note)
      VALUES (${organizationId}, ${ids.get(key)!}, 'MONTH', 2400, '2026-05-01', 'seed')
      ON CONFLICT (organization_id, user_id, period_type, effective_from) DO UPDATE SET target_points = EXCLUDED.target_points
    `;
  }
  return ids;
};

// Worklog ----------------------------------------------------------------------------------------------------

type LogRow = {
  line: number;
  staff: string;
  project: string;
  process: string;
  assignedDay: string;
  doneDay: string;
  shift: string;
  qty: number;
  credit: number;
};

const readWorklog = (): LogRow[] => {
  const records = parseCsv(readFileSync(logPath, "utf8"));
  const header = records[0]!.cells.map((cell) => cell.trim());
  const at = (name: string) => header.indexOf(name);
  return records.slice(1).map((record) => {
    const get = (name: string) => (record.cells[at(name)] ?? "").trim();
    return {
      line: record.line,
      staff: get("staff"),
      project: get("project"),
      process: get("process"),
      assignedDay: get("assigned_at"),
      doneDay: get("done_at"),
      shift: get("shift"),
      qty: Number(get("qty")),
      credit: Number(get("credit_per_image"))
    };
  });
};

const vn = (day: string, time: string) => new Date(`${day}T${time}:00+07:00`);

// Cleanup ------------------------------------------------------------------------------------------------------

const removePreviousSeed = async (sql: QuerySql, organizationId: string) => {
  await sql.begin(async (tx) => {
    const jobs = (
      await tx<{ id: string }[]>`
        SELECT j.id FROM production.jobs j
        JOIN production.entity_tags et ON et.organization_id = j.organization_id AND et.entity = 'JOB' AND et.entity_id = j.id
        JOIN production.tags tg ON tg.organization_id = et.organization_id AND tg.id = et.tag_id AND lower(tg.name) = 'seed'
        WHERE j.organization_id = ${organizationId}
      `
    ).map((row) => row.id);
    if (jobs.length === 0) {
      return;
    }
    // The score ledger and task history are append-only by trigger; the seed is the one place that may wipe them.
    await tx`SET LOCAL session_replication_role = replica`;
    await tx`DELETE FROM production.score_entries WHERE organization_id = ${organizationId} AND job_id = ANY(${jobs}::uuid[])`;
    await tx`DELETE FROM production.task_logs WHERE organization_id = ${organizationId} AND job_id = ANY(${jobs}::uuid[])`;
    await tx`DELETE FROM production.comments WHERE organization_id = ${organizationId} AND job_id = ANY(${jobs}::uuid[])`;
    await tx`
      DELETE FROM production.entity_tags WHERE organization_id = ${organizationId}
        AND ((entity = 'JOB' AND entity_id = ANY(${jobs}::uuid[]))
          OR (entity = 'TASK' AND entity_id IN (SELECT id FROM production.tasks WHERE job_id = ANY(${jobs}::uuid[]))))
    `;
    await tx`UPDATE production.feedbacks SET source_task_id = NULL WHERE organization_id = ${organizationId} AND job_id = ANY(${jobs}::uuid[])`;
    await tx`UPDATE production.tasks SET parent_task_id = NULL, feedback_id = NULL WHERE organization_id = ${organizationId} AND job_id = ANY(${jobs}::uuid[])`;
    await tx`DELETE FROM production.feedbacks WHERE organization_id = ${organizationId} AND job_id = ANY(${jobs}::uuid[])`;
    await tx`DELETE FROM production.tasks WHERE organization_id = ${organizationId} AND job_id = ANY(${jobs}::uuid[])`;
    await tx`DELETE FROM production.jobs WHERE organization_id = ${organizationId} AND id = ANY(${jobs}::uuid[])`;
    console.log(`Removed ${jobs.length} previous seed jobs.`);
  });
};

// Replay -------------------------------------------------------------------------------------------------------

type InflightKind = "PROCESSING" | "WAITING_QC" | "QC_FAIL" | "LATE" | "FEEDBACK";
const pickInflight = (): InflightKind => {
  const roll = random();
  return roll < 0.4 ? "PROCESSING" : roll < 0.7 ? "WAITING_QC" : roll < 0.85 ? "QC_FAIL" : roll < 0.95 ? "LATE" : "FEEDBACK";
};

const main = async () => {
  const sql = getSql();
  const organizationId = (await sql<{ id: string }[]>`SELECT id FROM public.organizations WHERE deleted_at IS NULL ORDER BY created_at LIMIT 1`)[0]?.id;
  if (!organizationId) {
    throw new Error("No organization found.");
  }
  const ids = await ensureAccounts(sql, organizationId);
  await removePreviousSeed(sql, organizationId);

  const imported = await sql.begin((tx) =>
    importCreditRules(tx, { organizationId, csv: readFileSync(rulesPath, "utf8"), effectiveFrom: "2026-05-01", createMissing: true, userId: ids.get("ADMIN01")! })
  );
  if (!imported.ok) {
    throw new Error(`Credit rules rejected: ${imported.errors.map((error) => `line ${error.line}: ${error.message}`).join("; ")}`);
  }
  console.log(`Credit rules: ${imported.imported} imported (new projects ${imported.createdProjects.length}, new processes ${imported.createdProcesses.length}).`);

  const seedTag = (
    await sql<{ id: string }[]>`
      INSERT INTO production.tags (organization_id, name, color) VALUES (${organizationId}, 'seed', 'slate')
      ON CONFLICT (organization_id, lower(name)) DO UPDATE SET active = true RETURNING id
    `
  )[0]!.id;
  const projects = new Map((await sql<{ id: string; code: string }[]>`SELECT id, code FROM production.projects WHERE organization_id = ${organizationId}`).map((row) => [row.code.toUpperCase(), row.id]));
  const processes = new Map((await sql<{ id: string; name: string; is_qc: boolean }[]>`SELECT id, name, is_qc FROM production.processes WHERE organization_id = ${organizationId} AND active`).map((row) => [row.name.toLowerCase(), row]));
  const shifts = new Map((await sql<{ id: string; name: string }[]>`SELECT id, name FROM production.shifts WHERE organization_id = ${organizationId} AND active`).map((row) => [row.name.toLowerCase(), row.id]));
  const workflow: Workflow = await loadWorkflowModel(sql, organizationId);
  const leaderId = ids.get("LEAD01")!;
  const leaderContext = await resolveAccessContext(leaderId);
  const status = (code: Parameters<typeof statusByCode>[1]) => statusByCode(workflow, code);

  const rows = readWorklog();
  const problems: string[] = [];
  for (const row of rows) {
    if (!projects.has(row.project.toUpperCase())) problems.push(`line ${row.line}: unknown project ${row.project}`);
    if (!processes.has(row.process.toLowerCase())) problems.push(`line ${row.line}: unknown process ${row.process}`);
    if (!shifts.has(row.shift.toLowerCase())) problems.push(`line ${row.line}: unknown shift ${row.shift}`);
    if (!ids.has(row.staff)) problems.push(`line ${row.line}: unknown staff ${row.staff}`);
  }
  if (problems.length > 0) {
    throw new Error(problems.slice(0, 20).join("\n"));
  }
  const isQcRow = (row: LogRow) => processes.get(row.process.toLowerCase())!.is_qc;
  // Staff who logged Checking rows act as QC (STAFF + QC, PLAN §2: "NV kiêm QC").
  const checkers = [...new Set(rows.filter(isQcRow).map((row) => ids.get(row.staff)!))];
  await sql`
    INSERT INTO production.user_roles (organization_id, user_id, role_code)
    SELECT ${organizationId}, user_id, 'QC' FROM unnest(${checkers}::uuid[]) AS user_id ON CONFLICT DO NOTHING
  `;

  // Jobs: (project, done day); total images = non-Checking quantity.
  const groups = new Map<string, LogRow[]>();
  for (const row of rows) {
    const key = `${row.project.toUpperCase()}|${row.doneDay}`;
    groups.set(key, [...(groups.get(key) ?? []), row]);
  }
  const lastDay = rows.reduce((max, row) => (row.doneDay > max ? row.doneDay : max), "");
  const inflightFrom = addDays(lastDay, -6);
  let clampedAssigned = 0;
  const outcome = { jobs: 0, tasks: 0, inflight: new Map<InflightKind, number>() };

  for (const [key, groupRows] of [...groups].sort(([a], [b]) => (a.split("|")[1]! < b.split("|")[1]! ? -1 : 1))) {
    const [projectCode, doneDay] = key.split("|") as [string, string];
    const workRows = groupRows.filter((row) => !isQcRow(row));
    if (workRows.length === 0) {
      continue; // A Checking row without work rows on that day has nothing to check.
    }
    await sql.begin(async (tx) => {
      const deadline = vn(doneDay, "18:00");
      const job = (
        await tx<{ id: string }[]>`
          INSERT INTO production.jobs (organization_id, project_id, code, leader_id, deadline, total_images, created_by, created_at)
          VALUES (${organizationId}, ${projects.get(projectCode)!}, ${`${projectCode} ${doneDay.replaceAll("-", "")}`}, ${leaderId}, ${deadline},
            ${workRows.reduce((sum, row) => sum + row.qty, 0)}, ${ids.get("ACC01")!}, ${vn(doneDay, "08:00")})
          RETURNING id
        `
      )[0]!;
      await tx`INSERT INTO production.entity_tags (organization_id, entity, entity_id, tag_id) VALUES (${organizationId}, 'JOB', ${job.id}, ${seedTag})`;
      const jobForTasks = { id: job.id, leader_id: leaderId, deadline, total_images: workRows.reduce((sum, row) => sum + row.qty, 0), qc_buffer_hours: 0 };

      // QC assignment from the Checking rows (SPEC §10.6): cover tasks in order until each checker's qty is used.
      const qcOf = new Array<string | null>(workRows.length).fill(null);
      for (const check of groupRows.filter(isQcRow)) {
        let remaining = check.qty;
        for (const [index, row] of workRows.entries()) {
          if (remaining <= 0) break;
          if (qcOf[index] || row.staff === check.staff) continue;
          qcOf[index] = ids.get(check.staff)!;
          remaining -= row.qty;
        }
      }

      const created: { task: TaskRow; row: LogRow }[] = [];
      for (const [index, row] of workRows.entries()) {
        let assignedDay = row.assignedDay;
        if (assignedDay > row.doneDay) {
          assignedDay = row.doneDay; // 25 worklog rows were "done" before "assigned".
          clampedAssigned += 1;
        }
        const { ids: taskIds } = await insertTasks(
          tx,
          leaderContext,
          workflow,
          jobForTasks,
          [
            {
              assigneeId: ids.get(row.staff)!,
              qcId: qcOf[index] ?? leaderId,
              processId: processes.get(row.process.toLowerCase())!.id,
              shiftId: shifts.get(row.shift.toLowerCase())!,
              qtyAssigned: row.qty,
              deadline: deadline.toISOString()
            }
          ],
          { kind: "NORMAL", feedbackId: null, defaultParentId: null, assignedAt: vn(assignedDay, "09:00") }
        );
        created.push({ task: await loadTask(tx, organizationId, taskIds[0]!), row });
      }

      for (const entry of created) {
        const { row } = entry;
        const assignee = ids.get(row.staff)!;
        const otHours = row.shift.toLowerCase() === "ot" ? Math.min(24, Math.max(0.1, Math.round((row.qty * row.credit) / 10 * 10) / 10)) : undefined;
        const kind = inflight > 0 && row.doneDay >= inflightFrom && random() < inflight ? pickInflight() : null;
        let task = entry.task;
        if (kind && kind !== "LATE") {
          // In-flight work is "now": move its deadline to tomorrow so only the LATE sample shows as late.
          const future = new Date(Date.now() + 86_400_000);
          await tx`UPDATE production.tasks SET deadline = ${future}, is_late = false WHERE id = ${task.id}`;
          task = { ...task, deadline: future, is_late: false };
        }
        const startAt = new Date(Math.min(vn(row.assignedDay > row.doneDay ? row.doneDay : row.assignedDay, "09:30").getTime(), vn(row.doneDay, "16:59").getTime()));
        task = await moveTask(tx, organizationId, workflow, task, status("PROCESSING"), assignee, null, { at: startAt });
        if (kind === "PROCESSING" || kind === "LATE") {
          outcome.inflight.set(kind, (outcome.inflight.get(kind) ?? 0) + 1);
          continue;
        }
        const doneAt = vn(row.doneDay, "17:00");
        task = await moveTask(tx, organizationId, workflow, task, status("DONE"), assignee, null, { qtyDone: row.qty, otHours, at: doneAt });
        task = await moveTask(tx, organizationId, workflow, task, status("WAITING_QC"), null, "Tự động chuyển sang chờ QC.", { at: doneAt });
        if (kind === "WAITING_QC") {
          outcome.inflight.set(kind, (outcome.inflight.get(kind) ?? 0) + 1);
          continue;
        }
        if (kind === "QC_FAIL") {
          await moveTask(tx, organizationId, workflow, task, status("PROCESSING"), task.qc_id, "Seed: QC trả lại một lần", { at: vn(row.doneDay, "17:20") });
          outcome.inflight.set(kind, (outcome.inflight.get(kind) ?? 0) + 1);
          continue;
        }
        task = await moveTask(tx, organizationId, workflow, task, status("CHECKED"), task.qc_id, null, { at: vn(row.doneDay, "17:30") });
        if (kind === "FEEDBACK") {
          // Client sends the job back: Complete → Delivering → Feedback (WRONG), the same worker redoes part of it.
          for (const code of ["COMPLETE", "DELIVERING"] as const) {
            task = await moveTask(tx, organizationId, workflow, task, status(code), code === "COMPLETE" ? leaderId : ids.get("ACC01")!, null, { at: vn(row.doneDay, "18:00") });
          }
          const feedback = (
            await tx<{ id: string }[]>`
              INSERT INTO production.feedbacks (organization_id, job_id, source_task_id, type, note, status, created_by, created_at)
              VALUES (${organizationId}, ${job.id}, ${task.id}, 'WRONG', 'Seed: khách báo sai màu', 'IN_PROGRESS', ${ids.get("ACC01")!}, ${vn(row.doneDay, "18:30")})
              RETURNING id
            `
          )[0]!;
          task = await moveTask(tx, organizationId, workflow, task, status("FEEDBACK"), ids.get("ACC01")!, "Feedback sai", { at: vn(row.doneDay, "18:30") });
          const redo = await insertTasks(
            tx,
            leaderContext,
            workflow,
            jobForTasks,
            [{ assigneeId: assignee, qcId: task.qc_id ?? leaderId, processId: task.process_id, shiftId: task.shift_id, qtyAssigned: Math.max(1, Math.ceil(row.qty / 3)), sourceTaskId: task.id }],
            { kind: "FB_WRONG", feedbackId: feedback.id, defaultParentId: task.id, assignedAt: vn(row.doneDay, "19:00") }
          );
          const fbTask = await loadTask(tx, organizationId, redo.ids[0]!);
          await moveTask(tx, organizationId, workflow, fbTask, status("PROCESSING"), assignee, null, { at: vn(row.doneDay, "19:10") });
          outcome.inflight.set(kind, (outcome.inflight.get(kind) ?? 0) + 1);
        }
      }
      await settleJob(tx, organizationId, workflow, job.id);
      // Historical replay must not flood inboxes: drop the notification events this transaction queued.
      await tx`DELETE FROM public.outbox_events WHERE created_at = now() AND aggregate_type LIKE 'production%' AND published_at IS NULL`;
      outcome.jobs += 1;
      outcome.tasks += created.length;
    });
  }

  if (inflight > 0) {
    // A few leave requests so the calendar has data (SPEC §10.8).
    const today = new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Ho_Chi_Minh" }).format(new Date());
    for (const [offset, key, status] of [[3, "NV01", "APPROVED"], [5, "NV05", "PENDING"], [9, "NV09", "APPROVED"]] as const) {
      await sql`
        DELETE FROM production.leave_requests WHERE organization_id = ${organizationId} AND user_id = ${ids.get(key)!} AND note = 'seed'
      `;
      await sql`
        INSERT INTO production.leave_requests (organization_id, user_id, from_date, to_date, part, note, status, decided_by, decided_at)
        VALUES (${organizationId}, ${ids.get(key)!}, ${addDays(today, offset)}::date, ${addDays(today, offset)}::date, 'FULL_DAY', 'seed', ${status},
          ${status === "APPROVED" ? leaderId : null}, ${status === "APPROVED" ? new Date() : null})
      `;
    }
  }

  // Reconciliation (PD-010): WORKER credits per person vs qty × credit_per_image of the non-Checking rows.
  const expected = new Map<string, number>();
  for (const row of rows.filter((item) => !isQcRow(item))) {
    expected.set(row.staff, (expected.get(row.staff) ?? 0) + Math.round(row.qty * row.credit * 100));
  }
  const actual = new Map(
    (
      await sql<{ user_id: string; cents: string }[]>`
        SELECT se.user_id, round(sum(se.credits) * 100)::bigint::text AS cents
        FROM production.score_entries se
        JOIN production.entity_tags et ON et.organization_id = se.organization_id AND et.entity = 'JOB' AND et.entity_id = se.job_id AND et.tag_id = ${seedTag}
        WHERE se.organization_id = ${organizationId} AND se.role = 'WORKER'
        GROUP BY se.user_id
      `
    ).map((row) => [row.user_id, Number(row.cents)])
  );
  console.log(`\nSeeded ${outcome.jobs} jobs / ${outcome.tasks} tasks (assigned date clamped on ${clampedAssigned} rows).`);
  if (inflight > 0) {
    console.log(`In flight: ${[...outcome.inflight].map(([kind, count]) => `${kind} ${count}`).join(", ")}`);
  }
  console.log("\nStaff  expected    recorded    diff");
  let mismatches = 0;
  for (const key of staffKeys) {
    const want = expected.get(key) ?? 0;
    const got = actual.get(ids.get(key)!) ?? 0;
    if (want !== got) mismatches += 1;
    console.log(`${key}   ${(want / 100).toFixed(2).padStart(9)}  ${(got / 100).toFixed(2).padStart(9)}  ${((got - want) / 100).toFixed(2).padStart(7)}`);
  }
  if (inflight === 0) {
    console.log(mismatches === 0 ? "\nReconciliation OK: every person matches to the cent." : `\nReconciliation FAILED for ${mismatches} people.`);
    process.exitCode = mismatches === 0 ? 0 : 1;
  } else {
    console.log("\n(In-flight work is not scored yet, so differences are expected with --inflight > 0.)");
  }
};

main()
  .catch((error: unknown) => {
    console.error(error instanceof Error ? error.message : error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await closeDatabase();
    await closeRedis();
  });
