/**
 * LOCAL DEVELOPMENT ONLY. Creates test accounts in the local Supabase Auth + app tables so
 * multi-user flows (assignment, chat, permissions) can be exercised.
 *
 * Passwords are generated once and stored in BE/.env.seed (git-ignored). Never run against
 * anything but the local stack: the script refuses non-loopback URLs.
 *
 *   npx tsx scripts/seed-dev-users.ts
 */
import { randomBytes } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";

import "dotenv/config";
import postgres from "postgres";

const seedFile = new URL("../.env.seed", import.meta.url);

const supabaseUrl = process.env.SUPABASE_URL ?? "";
const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY ?? "";
const databaseUrl = process.env.DATABASE_URL ?? "";

const isLoopback = (value: string) => {
  try {
    const host = new URL(value).hostname;
    return host === "127.0.0.1" || host === "localhost" || host === "[::1]";
  } catch {
    return false;
  }
};

if (!isLoopback(supabaseUrl) || !isLoopback(databaseUrl) || !serviceKey) {
  console.error("Refusing to seed: SUPABASE_URL and DATABASE_URL must point at the local stack.");
  process.exit(1);
}

type SeedUser = { key: string; email: string; displayName: string; role: "manager" | "member" };

const users: SeedUser[] = [
  { key: "MANAGER", email: "linh.manager@nesso.test", displayName: "Linh Trần", role: "manager" },
  { key: "MEMBER_A", email: "minh.dev@nesso.test", displayName: "Minh Nguyễn", role: "member" },
  { key: "MEMBER_B", email: "an.design@nesso.test", displayName: "An Phạm", role: "member" },
  { key: "MEMBER_C", email: "khoa.qa@nesso.test", displayName: "Khoa Lê", role: "member" }
];

const rolePermissions: Record<SeedUser["role"], string[]> = {
  manager: [
    "project.view", "project.create", "project.update", "project.manage_members",
    "list.view", "list.create", "list.update", "list.delete", "list.manage_status",
    "task.view", "task.create", "task.update", "task.delete", "task.assign",
    "status.view", "status.create", "status.update", "status.delete",
    "channel.view", "channel.create", "channel.update", "channel.manage_members",
    "knowledge.view"
  ],
  member: [
    "project.view", "list.view",
    "task.view", "task.create", "task.update", "task.assign",
    "status.view",
    "channel.view", "channel.create",
    "knowledge.view"
  ]
};

const loadPasswords = () => {
  const values = new Map<string, string>();
  if (existsSync(seedFile)) {
    for (const line of readFileSync(seedFile, "utf8").split(/\r?\n/)) {
      const match = /^SEED_([A-Z_]+)_PASSWORD=(.+)$/.exec(line.trim());
      if (match?.[1] && match[2]) {
        values.set(match[1], match[2]);
      }
    }
  }
  let changed = false;
  for (const user of users) {
    if (!values.has(user.key)) {
      values.set(user.key, `Dev-${randomBytes(9).toString("base64url")}`);
      changed = true;
    }
  }
  if (changed) {
    const body = users
      .map((user) => `SEED_${user.key}_EMAIL=${user.email}\nSEED_${user.key}_PASSWORD=${values.get(user.key)}`)
      .join("\n");
    writeFileSync(seedFile, `# Local dev test accounts (git-ignored). Generated by scripts/seed-dev-users.ts\n${body}\n`);
  }
  return values;
};

const admin = async (path: string, init: RequestInit) => {
  const response = await fetch(new URL(`/auth/v1/admin${path}`, supabaseUrl), {
    ...init,
    headers: { apikey: serviceKey, authorization: `Bearer ${serviceKey}`, "content-type": "application/json" }
  });
  const text = await response.text();
  return { status: response.status, body: text ? (JSON.parse(text) as unknown) : null };
};

const findAuthUserId = async (sql: postgres.Sql, email: string) => {
  const rows = await sql<{ id: string }[]>`SELECT id FROM auth.users WHERE lower(email) = lower(${email}) LIMIT 1`;
  return rows[0]?.id;
};

const main = async () => {
  const passwords = loadPasswords();
  const sql = postgres(databaseUrl, { max: 1 });

  try {
    const org = (await sql<{ id: string }[]>`SELECT id FROM public.organizations WHERE deleted_at IS NULL ORDER BY created_at LIMIT 1`)[0];
    if (!org) {
      throw new Error("No organization found. Apply the bootstrap SQL first.");
    }

    const roleIds = new Map<string, string>();
    for (const [key, permissions] of Object.entries(rolePermissions)) {
      const name = key === "manager" ? "Manager" : "Member";
      const role = (
        await sql<{ id: string }[]>`
          INSERT INTO public.roles (organization_id, key, name, description, is_system)
          VALUES (${org.id}, ${key}, ${name}, ${`${name} role (dev seed)`}, false)
          ON CONFLICT (organization_id, key) WHERE deleted_at IS NULL DO UPDATE SET name = EXCLUDED.name
          RETURNING id
        `
      )[0]!;
      roleIds.set(key, role.id);
      await sql`
        INSERT INTO public.role_permissions (organization_id, role_id, permission_key)
        SELECT ${org.id}, ${role.id}, unnest(${permissions}::text[])
        ON CONFLICT DO NOTHING
      `;
    }

    for (const user of users) {
      let userId = await findAuthUserId(sql, user.email);
      if (!userId) {
        const created = await admin("/users", {
          method: "POST",
          body: JSON.stringify({
            email: user.email,
            password: passwords.get(user.key),
            email_confirm: true,
            user_metadata: { display_name: user.displayName }
          })
        });
        if (created.status >= 300) {
          throw new Error(`Creating ${user.email} failed with ${created.status}`);
        }
        userId = await findAuthUserId(sql, user.email);
      }
      if (!userId) {
        throw new Error(`User ${user.email} was not created`);
      }

      await sql`
        INSERT INTO public.app_users (id, email, display_name)
        VALUES (${userId}, ${user.email}, ${user.displayName})
        ON CONFLICT (id) DO UPDATE SET display_name = EXCLUDED.display_name, email = EXCLUDED.email
      `;
      await sql`
        INSERT INTO public.organization_memberships (organization_id, user_id, role_id, status, joined_at)
        VALUES (${org.id}, ${userId}, ${roleIds.get(user.role)!}, 'active', now())
        ON CONFLICT (organization_id, user_id) WHERE deleted_at IS NULL
        DO UPDATE SET role_id = EXCLUDED.role_id, status = 'active'
      `;
      console.log(`Seeded ${user.email} (${user.role})`);
    }

    console.log("Done. Credentials are in BE/.env.seed");
  } finally {
    await sql.end();
  }
};

main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
